/**
 * Sync every video + Short from the Venus Foundation YouTube channel into
 * src/content/generated/youtube.ts using the official YouTube Data API v3.
 *
 * Usage:
 *   1. Get a free API key: https://console.cloud.google.com → enable
 *      "YouTube Data API v3" → create an API key.
 *   2. Put it in a .env file at the project root:   YOUTUBE_API_KEY=xxxxx
 *      (or pass it inline: YOUTUBE_API_KEY=xxx npm run sync:shorts)
 *   3. Run:  npm run sync:shorts
 *
 * No key is committed; .env is gitignored.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

/** Channel handle (without the @). Override with: npm run sync:shorts -- <handle> */
const HANDLE = process.argv[2]?.replace(/^@/, "") || "FoundationVenus";
/** Videos at or under this length are treated as Shorts. */
const SHORT_MAX_SECONDS = 180;
const OUT = resolve(ROOT, "src/content/generated/youtube.ts");

/** Minimal .env loader (avoids a dependency). */
function loadEnv() {
  try {
    const text = readFileSync(resolve(ROOT, ".env"), "utf8");
    for (const line of text.split("\n")) {
      const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/);
      if (m && !process.env[m[1]]) {
        process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
      }
    }
  } catch {
    /* no .env — rely on real env vars */
  }
}

const API = "https://www.googleapis.com/youtube/v3";

async function api(path, params) {
  const url = new URL(`${API}/${path}`);
  for (const [k, v] of Object.entries(params)) {
    url.searchParams.set(k, v);
  }
  const res = await fetch(url);
  const json = await res.json();
  if (!res.ok) {
    throw new Error(`${res.status} ${json.error?.message || res.statusText}`);
  }
  return json;
}

/** Parse an ISO-8601 duration (PT#H#M#S) to seconds. */
function isoToSeconds(iso) {
  const m = iso.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!m) {
    return 0;
  }
  return (+(m[1] || 0)) * 3600 + (+(m[2] || 0)) * 60 + (+(m[3] || 0));
}

async function main() {
  loadEnv();
  const key = process.env.YOUTUBE_API_KEY;
  if (!key) {
    console.error("\nMissing YOUTUBE_API_KEY. Add it to .env or pass it inline.\n");
    process.exit(1);
  }

  console.log(`Resolving @${HANDLE}…`);
  const ch = await api("channels", { part: "contentDetails,snippet", forHandle: HANDLE, key });
  const channel = ch.items?.[0];
  if (!channel) {
    throw new Error(`Channel @${HANDLE} not found.`);
  }
  const uploads = channel.contentDetails.relatedPlaylists.uploads;
  console.log(`Channel: ${channel.snippet.title} (${channel.id})`);

  // 1) collect every uploaded video id + title
  const items = [];
  let pageToken = "";
  do {
    const page = await api("playlistItems", {
      part: "snippet,contentDetails",
      playlistId: uploads,
      maxResults: "50",
      key,
      ...(pageToken ? { pageToken } : {}),
    });
    for (const it of page.items) {
      items.push({ id: it.contentDetails.videoId, title: it.snippet.title.trim() });
    }
    pageToken = page.nextPageToken || "";
  } while (pageToken);
  console.log(`Found ${items.length} uploads. Fetching durations…`);

  // 2) batch-fetch durations to classify Shorts vs regular videos
  const byId = new Map(items.map((v) => [v.id, v]));
  const videos = [];
  for (let i = 0; i < items.length; i += 50) {
    const batch = items.slice(i, i + 50).map((v) => v.id);
    const det = await api("videos", { part: "contentDetails", id: batch.join(","), key });
    for (const v of det.items) {
      const seconds = isoToSeconds(v.contentDetails.duration);
      videos.push({
        id: v.id,
        title: byId.get(v.id)?.title || "",
        thumb: `https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`,
        seconds,
        short: seconds > 0 && seconds <= SHORT_MAX_SECONDS,
      });
    }
  }

  const shorts = videos.filter((v) => v.short).length;
  const body = `/**
 * AUTO-GENERATED by \`npm run sync:shorts\`. Manual edits are overwritten.
 * Channel: @${HANDLE} · ${videos.length} videos (${shorts} shorts) · synced ${new Date().toISOString().slice(0, 10)}
 */
export interface YtVideo {
  id: string;
  title: string;
  thumb: string;
  seconds: number;
  short: boolean;
}

export const youtubeVideos: YtVideo[] = ${JSON.stringify(videos, null, 2)};
`;
  writeFileSync(OUT, body);
  console.log(`✓ Wrote ${videos.length} videos (${shorts} shorts) → ${OUT}`);
}

main().catch((err) => {
  console.error(`\n✗ ${err.message}\n`);
  process.exit(1);
});
